%CIRCLECI 2.1
---
- &default
<<: *defaults
version: 2.1
description: >
  this is a description of this config file
commands:
  say_hello:
    description: >
      this is a description of this command `say_hello`
    parameters:
      image-name:
        type: string
        default: "node"
      image-version:
        type: integer
        default: 10.14.1
    docker:
      - image: circleci/<<parameters.image-name>>:<<parameters.image-version>>
    steps:
      - run: {{ .BuildNum }}-{{ .Branch }}-{{ .Revision }}-{{ .Environment.VAR_NAME }}-{{ checksum ".git" }}
...