%CIRCLECI 2.1
---
version: 2.1
description: >
  This is a description of this config
environment:
parallelism:
docker:
macos:
machine:
branches:
resource_class:
steps:
  run:
    command:
    name:
    shell:
    environment:
    background:
    working_directory:
    no_output_timeout:
    when:
when:
unless:
key:
keys:
path:
paths:
setup_remote_docker:
docker_layer_caching:
restore_cache:
save_cache:

jobs:
orbs:
commands:
condition:
executors:
workflows:
  version:
  triggers:
    schedule:
      cron:
      filters:
        branches:
          tags:
          only:
          ignore:
  jobs:
    job_name:
      requires:
      name:
      context:
      type:
deploy:
store_artifacts:
store_test_artifacts:
destination:
persist_to_workspace:
atach_workspace:
root:
at:
add_ssh_keys:
fingerprints:
image:
when: on_failure
when: always
when: on_success
when: on_warning

  - run:
      name:
      command:
<<parameters.custom_checkout>>
{{ .Branch }}
{{ .Environment.TAG_NAME }}
{{ checksum ".git" }}
{{ epoch }}
true
false
n
y
no
yes
on
off
...