%CIRCLECI 2.1
---
version: 2.1
aliases:
  - &restore-repo-cache
    restore_cache:
      keys:
        - v1-repo-{{ .Branch }}-{{ .Environment.VERSION }}-{{ .Revision }}-{{ checksum ".git" }}
  - &restore-bundle-cache
    restore_cache:
      keys:
        - v1-bundle-{{ .Branch }}-{{ .Environment.VERSION }}-{{ .Revision }}-{{ checksum "vendor/bundle" }}
  - &restore-yarn-cache
    restore_cache:
      keys:
        - v1-yarn-{{ .Branch }}-{{ .Environment.VERSION }}-{{ .Revision }}-{{ checksum "yarn.lock" }}
  - &defaults
    docker:
      - image: circleci/ruby:2.5.3
      - image: circleci/node:10
    working_directory: ~/sublime-circle-ci

jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Installing Dependencies from RubyGems
          command: bundle install
      - run:
          name: Installing Dependencies from Npm
          command: yarn install
workflows:
  version: 2.1
  checkout_code:
    jobs:
      - checkout_code
...