%CIRCLECI 2.1
---
version: 2.1
jobs:
  checkout_gems:
    docker:
      - image: circleci/ruby:2.5.3
    working_directory: ~/sublime-circle-ci
    steps:
      - checkout
      - run:
          name: Installing Dependencies from RubyGems
          command: bundle install
  checkout_yarn:
    docker:
      - image: circleci/node:10
    working_directory: ~/sublime-circle-ci
    steps:
      - run:
          name: Installing Dependencies from Yarn
          command: yarn install
workflows:
  version: 2.1
  checkout_code:
    jobs:
      - checkout_gems
      - checkout_yarn
...